name: radio_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  http: ^1.2.1
  dartz: ^0.10.1
  get_it: ^7.7.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  mockito: ^5.4.4
  bottom_bar_matu: ^1.5.0
  audioplayers: ^6.0.0
  palette_generator: ^0.3.3+4
  text_scroll: ^0.2.0
  pulsator: ^1.0.0+2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
